name: Preparing to patch
runs:
  using: "composite"
  steps:
    - name: Set up jdk
      uses: actions/setup-java@v5.1.0
      with:
        distribution: 'zulu'
        java-version: '21'
    - name: Install Android build tools for aapt
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y aapt
#    - name: Setup Cloudflare Warp
#      shell: bash
#      run: bash src/etc/cf_warp.sh
